version: "3.7"

services:
  postgres:
    image: postgres:14.5
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh

  webserver:
    build:
      context: .
    depends_on:
      - minio
      - postgres
    ports:
      - 8089:8080
    env_file: 
      - .env

  minio:
    image: minio/minio:RELEASE.2022-10-08T20-11-00Z
    ports:
      - 9001:9001
      - 9000:9000
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data

volumes:
  minio-data: